server:
  command port: 9000
  notification port: 9001

io:
  type: Gainer
  com: 

...
# the following lines will be ignored
# please remove "..." to activate multiple I/O module settings
  -
    type: Arduino
    com: COM4
